import React from 'react';
import { Github, Heart, Code, Users, Shield, Lightbulb, ExternalLink } from 'lucide-react';

export default function AboutPage() {
  const handleOpenIssue = () => {
    window.open('https://github.com/daveklee/calorieclimb.com/issues/new', '_blank');
  };

  const handleOpenRepository = () => {
    window.open('https://github.com/daveklee/calorieclimb.com', '_blank');
  };

  return (
    <div className="p-4">
      <div className="max-w-4xl mx-auto">
        {/* Hero Section */}
        <div className="bg-gradient-to-r from-green-400 to-blue-500 rounded-lg shadow-lg p-8 mb-8 text-white">
          <div className="text-center">
            <div className="text-6xl mb-4">👨‍💻🍎</div>
            <h1 className="text-4xl font-bold mb-4">About Calorie Climb</h1>
            <p className="text-xl">
              A fun, educational game that teaches kids about nutrition through interactive gameplay
            </p>
          </div>
        </div>

        {/* Main Content */}
        <div className="space-y-8">
          {/* Creator's Story */}
          <div className="bg-white rounded-lg shadow-lg p-8">
            <div className="flex items-center space-x-3 mb-6">
              <Heart className="w-8 h-8 text-red-500" />
              <h2 className="text-3xl font-bold text-gray-800">The Story Behind This Game</h2>
            </div>
            
            <div className="prose prose-lg max-w-none text-gray-700 space-y-4">
              <p className="text-lg leading-relaxed">
                Hi, I'm Dave! I made this website because my kids were asking me a lot of questions about foods, 
                and I didn't have great answers. When they asked me, "What's more healthy -- pizza or chicken nuggets?" 
                I figured I should work harder to expose them to more food options.
              </p>
              
              <p className="text-lg leading-relaxed">
                This game combines the fun of a counting challenge with nutritional education. Kids learn about 
                different foods, their calorie content, and health ratings while playing an engaging game that 
                encourages exploration of diverse food choices.
              </p>
            </div>
          </div>

          {/* Important Disclaimer */}
          <div className="bg-yellow-50 border-l-4 border-yellow-400 rounded-lg shadow-lg p-8">
            <div className="flex items-center space-x-3 mb-4">
              <Shield className="w-8 h-8 text-yellow-600" />
              <h2 className="text-2xl font-bold text-yellow-800">Important Disclaimer</h2>
            </div>
            
            <div className="text-yellow-800 space-y-3">
              <p className="font-medium">
                Please keep in mind, I am not a nutritionist or doctor, and this website is not meant to be medical advice. 
                Any text about various foods is generated by AI, and should be validated with a professional before being 
                used to feed your family!
              </p>
              
              <p>
                Also, I have done my best to make this game kid friendly and exclude any references to adult beverages, 
                but there's always a chance something strange slips through. If you notice anything inappropriate, 
                please let me know so I can fix it!
              </p>
            </div>
          </div>

          {/* Features */}
          <div className="bg-white rounded-lg shadow-lg p-8">
            <div className="flex items-center space-x-3 mb-6">
              <Lightbulb className="w-8 h-8 text-blue-500" />
              <h2 className="text-3xl font-bold text-gray-800">What Makes This Special</h2>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-green-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-green-800 mb-3">🥗 Real Food Data</h3>
                <p className="text-green-700">
                  Uses the official USDA Food Data Central database for accurate nutritional information 
                  about thousands of foods.
                </p>
              </div>
              
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-800 mb-3">🤖 AI-Enhanced Learning</h3>
                <p className="text-blue-700">
                  Provides educational feedback about food choices using AI to make learning 
                  fun and engaging for kids.
                </p>
              </div>
              
              <div className="bg-purple-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-purple-800 mb-3">🎮 Gamified Education</h3>
                <p className="text-purple-700">
                  Turns nutrition education into an exciting climbing game that keeps kids 
                  engaged while they learn.
                </p>
              </div>
              
              <div className="bg-orange-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-orange-800 mb-3">👨‍👩‍👧‍👦 Family Friendly</h3>
                <p className="text-orange-700">
                  Designed with safety in mind, filtering out inappropriate content and 
                  focusing on positive food education.
                </p>
              </div>
            </div>
          </div>

          {/* Open Source */}
          <div className="bg-white rounded-lg shadow-lg p-8">
            <div className="flex items-center space-x-3 mb-6">
              <Code className="w-8 h-8 text-purple-500" />
              <h2 className="text-3xl font-bold text-gray-800">Open Source Project</h2>
            </div>
            
            <div className="space-y-4 text-gray-700">
              <p className="text-lg">
                This project is open source and available for the community to contribute to and improve! 
                Whether you're a developer, educator, nutritionist, or parent, your input is valuable.
              </p>
              
              <div className="bg-gray-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-gray-800 mb-4">How to Contribute</h3>
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <Github className="w-5 h-5 text-gray-600" />
                    <span>Report bugs or request features by opening issues on GitHub</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Users className="w-5 h-5 text-gray-600" />
                    <span>Submit pull requests to improve the code or add new features</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Heart className="w-5 h-5 text-gray-600" />
                    <span>Share feedback and suggestions for educational improvements</span>
                  </div>
                </div>
              </div>
              
              <div className="flex flex-col sm:flex-row gap-4">
                <button
                  onClick={handleOpenRepository}
                  className="flex items-center justify-center space-x-2 bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-lg font-medium transition-colors"
                >
                  <Github className="w-5 h-5" />
                  <span>View on GitHub</span>
                  <ExternalLink className="w-4 h-4" />
                </button>
                
                <button
                  onClick={handleOpenIssue}
                  className="flex items-center justify-center space-x-2 bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-lg font-medium transition-colors"
                >
                  <Github className="w-5 h-5" />
                  <span>Open Issue</span>
                  <ExternalLink className="w-4 h-4" />
                </button>
              </div>
              
              <div className="bg-blue-50 border border-blue-200 p-4 rounded-lg">
                <p className="text-blue-800 font-medium">
                  💡 Found a bug or have a feature request? Click "Open Issue" above to let us know!
                </p>
              </div>
            </div>
          </div>

          {/* Technology Stack */}
          <div className="bg-white rounded-lg shadow-lg p-8">
            <h2 className="text-2xl font-bold text-gray-800 mb-6">Built With</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="text-center p-4 bg-blue-50 rounded-lg">
                <div className="text-2xl mb-2">⚛️</div>
                <div className="font-medium text-blue-800">React</div>
              </div>
              <div className="text-center p-4 bg-blue-50 rounded-lg">
                <div className="text-2xl mb-2">🎨</div>
                <div className="font-medium text-blue-800">Tailwind CSS</div>
              </div>
              <div className="text-center p-4 bg-green-50 rounded-lg">
                <div className="text-2xl mb-2">🏛️</div>
                <div className="font-medium text-green-800">USDA API</div>
              </div>
              <div className="text-center p-4 bg-purple-50 rounded-lg">
                <div className="text-2xl mb-2">🤖</div>
                <div className="font-medium text-purple-800">Perplexity AI</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}